name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  path: ^1.6.4
  provider: ^4.0.1
  path_provider: ^1.5.1
  url_launcher: ^5.4.1   #開啟email phone url...
  flutter_i18n: ^0.8.3   #多國語言
  #----------store data----------#
  shared_preferences: ^0.5.6
  sqflite: ^1.2.0
  #----------internet----------#
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  http: ^0.12.0+4
  html: ^0.14.0+3  #html解析器
  #requests: ^3.0.3
  #----------UI----------#
  fluttertoast: ^3.1.3
  giffy_dialog: ^1.6.1
  awesome_dialog: ^0.1.1
  flutter_slidable: ^0.4.7  #email使用抽屜
  configurable_expansion_tile: ^1.0.0
  #direct_select_flutter: ^1.0.5
  #gzx_dropdown_menu: ^1.0.3
  #----------WebView----------#
  webview_flutter: 0.3.19+5
  flutter_webview_plugin: ^0.3.10+1
  #---------icon----------#
  font_awesome_flutter: ^8.5.0
  community_material_icon: ^3.5.95
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  #---------json----------#
  json_annotation: ^3.0.1
  #----------other----------#
  back_button_interceptor: ^4.2.3     #攔截返回鍵訊息
  sprintf: ^4.0.2
  random_color: ^1.0.3
  big5: ^0.0.4     #big5 decode encode
  quiver: ^2.0.5   #hashcode
  intl: ^0.16.0    #DateTime to String
  keyboard_visibility: ^0.5.6
  #----------html viewer----------#
  flutter_html: ^0.11.1
  flutter_widget_from_html_core: ^0.3.2+1
  #----------animation----------#
  page_transition: ^1.1.5                #頁面切換動畫
  flutter_staggered_animations: ^0.1.2   #listView or gridView動畫
  #----------download----------#
  flutter_downloader: ^1.4.1
  open_file: ^3.0.1
  permission_handler: ^4.2.0+hotfix.3
  mime_type: ^0.2.5
  video_player: ^0.10.2+5
  #----------Widget----------#
  flutter_selectable_text: ^0.3.1        #提供可以複製的TEXT
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.0.0
  auto_size_text: ^2.1.0
  native_color: ^1.2.0+1
  easy_dialog: ^1.0.5
  table_calendar: ^2.2.2
  flutter_range_slider: ^1.4.0
  step_slider: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_automation: ^1.3.1
  #---------json----------#
  build_runner: ^1.7.3
  json_serializable: ^3.2.5


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/gif/

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf