name: flutter_app
description: A new Flutter application.

version: 1.2.13+14

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.7.0
  provider: ^4.3.2+2
  path_provider: ^1.6.22
  url_launcher: 5.5.0
  #開啟email phone url...
  logger: ^0.9.4
  #顯示Log
  sprintf: ^5.0.0
  flutter_local_notifications: 1.4.3
  #通知欄  需修改android原始碼
  rxdart: 0.24.1
  #通知欄有使用到
  video_player: ^0.10.12+5
  chewie: 0.9.10
  after_init: 0.1.2
  android_intent: ^0.3.7+6
  device_info: ^0.4.2+9
  html_unescape: ^1.0.2
  #處理HTML特殊字
  local_auth: ^0.6.3+3
  #驗證身分指紋
  version: 1.2.0
  #版本比較
  #----------store data----------#
  shared_preferences: ^0.5.12+2
  flutter_cache_manager: ^2.0.0
  #----------internet----------#
  dio: ^3.0.10
  #網路get post API
  dio_cookie_manager: 1.0.0
  #用於產生cookie_jar與dio接口
  cookie_jar: 1.0.1
  #可儲存式cookies
  html: ^0.14.0+4
  #html解析器
  connectivity: ^2.0.0
  github: ^7.0.3
  bloc: ^6.1.0
  #----------WebView----------#
  flutter_webview_plugin: 0.3.11
  #---------icon----------#
  eva_icons_flutter: 2.0.1
  #https://akveo.github.io/eva-icons/#/
  flutter_icons: 1.1.0
  #https://oblador.github.io/react-native-vector-icons/
  #---------json----------#
  json_annotation: ^3.1.0
  #----------other----------#
  back_button_interceptor: ^4.4.0
  #攔截返回鍵訊息
  big5:      #big5 decode encode
    path: plugins/big5-dart
  intl: 0.16.1
  #DateTime to String
  package_info: ^0.4.3
  #檢測app版本用於檢查更新
  #----------html viewer----------#
  flutter_widget_from_html_core: ^0.5.1+3
  #----------animation----------#
  page_transition: ^1.1.7+2
  #頁面切換動畫
  flutter_staggered_animations: 0.1.2
  #listView or gridView動畫
  #----------download----------#
  flutter_downloader: ^1.5.2
  #下載app更新
  open_file: ^3.0.3
  permission_handler: 5.0.1+1
  mime_type: 0.3.2
  #----------Widget----------#
  pull_to_refresh: ^1.6.2
  #提供ListView可下拉式更新並且可動態加載
  cached_network_image: ^2.3.3
  #用url顯示圖片
  auto_size_text: 2.1.0
  #課表顯示有用到
  table_calendar: ^2.3.0
  #顯示行事曆
  flutter_xlider: 3.4.0
  #語言切換用
  fluttertoast: ^7.1.1
  #Toast
  awesome_dialog: ^1.2.1
  #顯示Error時用到
  flutter_slidable: ^0.5.7
  #email使用可左右滑抽屜
  flutter_spinkit: 4.1.2+1
  #等待動畫
  flutter_markdown: ^0.5.0

  # Firebase
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
  firebase_remote_config: ^0.4.0+2
dependency_overrides:
  http_parser:
    path: plugins/http_parser


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_automation: ^1.4.0
  #---------json----------#
  build_runner: ^1.10.4
  json_serializable: ^3.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
    - family: MyFont
      fonts:
        - asset: fonts/GenSenRounded-R.ttc
          weight: 400
        - asset: fonts/GenSenRounded-B.ttc
          weight: 700

flutter_intl:
  enabled: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios-icon.png"
  image_path_android: "assets/launcher/android-icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"