name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  path: ^1.6.4
  provider: ^4.0.1
  path_provider : ^1.5.1
  url_launcher: ^5.4.1
  flutter_i18n: ^0.8.3
  #----------store data----------#
  shared_preferences: ^0.5.6
  sqflite: ^1.2.0
  #----------internet----------#
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  http: ^0.12.0+4
  html: ^0.14.0+3
  #requests: ^3.0.3
  #----------UI----------#
  fluttertoast: ^3.1.3
  giffy_dialog: ^1.6.1
  awesome_dialog: ^0.1.1
  flutter_slidable: ^0.4.7
  #direct_select_flutter: ^1.0.5
  #gzx_dropdown_menu: ^1.0.3
  #----------WebView----------#
  webview_flutter: 0.3.19+5
  flutter_webview_plugin: ^0.3.10+1
  #---------icon----------#
  font_awesome_flutter: ^8.5.0
  community_material_icon: ^3.5.95
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  #---------json----------#
  #analyzer : ^0.39.4
  #json_serializable: ^3.2.5
  json_annotation: ^3.0.1
  #----------other----------#
  cached_network_image: ^2.0.0
  sprintf: ^4.0.2
  pull_to_refresh: ^1.5.8
  random_color: ^1.0.3
  big5: ^0.0.4     #big5 decode encode
  quiver: ^2.0.5   #hashcode
  intl: ^0.16.0    #DateTime to String
  #----------html viewer----------#
  flutter_html: ^0.11.1
  flutter_widget_from_html_core : ^0.3.2+1
  #----------animation----------#
  page_transition: ^1.1.5
  flutter_staggered_animations: ^0.1.2
  flutter_selectable_text: ^0.3.1
  #----------download----------#
  flutter_downloader: ^1.4.1
  open_file: ^3.0.1
  permission_handler: ^4.2.0+hotfix.3
  mime_type: ^0.2.5
  video_player: ^0.10.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_automation: ^1.3.1
  #---------json----------#
  build_runner: ^1.7.3
  json_serializable: ^3.2.5


flutter_icons:
  android: true
  ios: true
  image_path: "assets/ui.icon/exclamation_mark_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/gif/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
