name: flutter_app
description: A new Flutter application.

version: 1.2.6+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  path: ^1.6.4
  provider: ^4.1.1
  path_provider: ^1.6.7
  url_launcher: ^5.4.5   #開啟email phone url...
  logger: ^0.9.1         #顯示Log
  sprintf: ^4.0.2
  flutter_local_notifications: ^1.4.3  #通知欄
  hex: ^0.1.2
  rxdart: ^0.24.0 #通知欄有使用到
  flutter_ijkplayer: ^0.3.5+1
  after_init: ^0.1.2
  android_intent: ^0.3.7+2
  device_info: ^0.4.2+3
  #----------store data----------#
  shared_preferences: ^0.5.7+1
  flutter_cache_manager: ^1.2.2
  #----------internet----------#
  dio: ^3.0.9      #網路get post API
  dio_cookie_manager: ^1.0.0  #用於產生cookie_jar與dio接口
  cookie_jar: ^1.0.1  #可儲存式cookies
  http: ^0.12.1  #網路get post API (無使用)
  html: ^0.14.0+3  #html解析器
  #----------WebView----------#
  webview_flutter: 0.3.21
  flutter_webview_plugin: ^0.3.11
  #---------icon----------#
  eva_icons_flutter: ^2.0.0
  flutter_icons: ^1.0.0+1
  #---------json----------#
  json_annotation: ^3.0.1
  #----------other----------#
  back_button_interceptor: ^4.2.3     #攔截返回鍵訊息
  big5: ^0.0.4     #big5 decode encode
  quiver: ^2.1.3   #hashcode
  intl: ^0.16.1    #DateTime to String
  package_info: ^0.4.0+17  #檢測app版本用於檢查更新
  #----------html viewer----------#
  #flutter_html: ^0.11.1
  flutter_widget_from_html_core: ^0.3.3+3
  #----------animation----------#
  page_transition: ^1.1.5                #頁面切換動畫
  flutter_staggered_animations: ^0.1.2   #listView or gridView動畫
  #----------download----------#
  flutter_downloader: ^1.4.4  #下載app更新
  open_file: ^3.0.1
  permission_handler: ^5.0.0+hotfix.5
  mime_type: ^0.3.0
  #----------Widget----------#
  pull_to_refresh: ^1.5.8  #提供ListView可下拉式更新並且可動態加載
  cached_network_image: ^2.2.0+1  #用url顯示圖片
  auto_size_text: ^2.1.0  #課表顯示有用到
  table_calendar: ^2.2.3    #顯示行事曆
  flutter_xlider: ^3.4.0    #語言切換用
  fluttertoast: ^4.0.1      #Toast
  awesome_dialog: ^0.1.4  #顯示Error時用到
  flutter_slidable: ^0.5.4  #email使用可左右滑抽屜

  # Firebase
  firebase_core: 0.4.4  # 0.4.4+3 版本在 iOS 尚有問題
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_automation: ^1.3.3
  #---------json----------#
  build_runner: ^1.9.0
  json_serializable: ^3.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/gif/

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
    - family: GenSenMaruGothicTW
      fonts:
        - asset: fonts/GenSenMaruGothicTW-Regular.ttf
          weight: 400
        - asset: fonts/GenSenMaruGothicTW-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios-icon.png"
  image_path_android: "assets/launcher/android-icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"